###

GET http://localhost:3000/api/blogposts HTTP/1.1

###

GET http://localhost:3000/api/blogposts/87 HTTP/1.1

### Get all users

GET http://localhost:3000/api/user HTTP/1.1

###

GET http://localhost:3000/api/user/8 HTTP/1.1

###
GET http://localhost:3000/api/todo HTTP/1.1

###
GET http://localhost:3000/api/todo/8 HTTP/1.1